apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f odoo-compose.yaml
      --out ../../03_kubernetes/odoo/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
  - name: "8069"
    port: 8069
    targetPort: 8069
    nodePort: 30069
  selector:
    io.kompose.service: web
  type: NodePort
