version: '3.9'
services:
  pgadmin4:
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=toto@toto.com
      - PGADMIN_DEFAULT_PASSWORD=odoo
    image: dpage/pgadmin4
    ports:
      - 8081:80
    networks:
      - ic-webapp-networks

networks:
  ic-webapp-networks:
    external: true