---
- name: kubecongi file 
  hosts: k3s
  tasks:
    - name: copy file
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ./kubeconfig-k3s.yaml
        flat: yes
    - name: update kubeconfig file
      local_action:
        module: lineinfile
        path: ./kubeconfig-k3s.yaml
        regexp: '    server: https://127.0.0.1:6443'
        line:'     server: https://{{ ansible_host }}:6443'